"""TMDB API client — fetches Bollywood movies via the Discover endpoint."""

from __future__ import annotations

import logging
from typing import Any

import httpx

logger = logging.getLogger(__name__)


def _era_from_year(year: int | None) -> str:
    if year is None:
        return "unknown"
    if year < 2000:
        return "90s"
    if year < 2010:
        return "2000s"
    if year < 2020:
        return "2010s"
    return "2020s"


def _word_count(title: str) -> int:
    return len((title or "").split())


def compute_difficulty(
    popularity: float,
    word_count: int,
    year: int | None,
    vote_count: int,
) -> str:
    """
    Multi-factor difficulty scoring for TMDB movies (no OpenAI needed).

    Factors (all normalised to 0-1, higher = harder):
    - popularity:  inverse — less popular means harder
    - word_count:  more words in title = harder to act out
    - age:         older films are less well-known
    - vote_count:  fewer votes = more obscure

    Returns 'easy' | 'medium' | 'hard'.
    """
    pop_score = 1.0 - min(popularity / 500.0, 1.0)
    word_score = min(max(word_count - 1, 0) / 5.0, 1.0)
    age_score = max(0.0, min((2024 - (year or 2000)) / 40.0, 1.0))
    vote_score = 1.0 - min(vote_count / 2000.0, 1.0)

    score = 0.5 * pop_score + 0.15 * word_score + 0.15 * age_score + 0.2 * vote_score

    if score < 0.35:
        return "easy"
    if score < 0.65:
        return "medium"
    return "hard"


def _parse_movie(raw: dict[str, Any]) -> dict[str, Any]:
    """Normalize a raw TMDB movie object into our internal schema."""
    raw_date: str = raw.get("release_date") or ""
    year: int | None = int(raw_date[:4]) if len(raw_date) >= 4 and raw_date[:4].isdigit() else None
    title: str = raw.get("title") or raw.get("original_title") or ""
    popularity = float(raw.get("popularity", 0))
    vote_count = int(raw.get("vote_count") or 0)
    wc = _word_count(title)

    return {
        "id": str(raw.get("id", "")),
        "title": title,
        "year": year,
        "language": raw.get("original_language", "hi"),
        "original_language": raw.get("original_language", "hi"),
        "popularity": popularity,
        "vote_count": vote_count,
        "word_count": wc,
        "poster_path": raw.get("poster_path"),
        "source": "tmdb",
        "era": _era_from_year(year),
        "tmdb_id": raw.get("id"),
        "difficulty": compute_difficulty(popularity, wc, year, vote_count),
    }


def apply_difficulty_filter(movies: list[dict[str, Any]], difficulty: str) -> list[dict[str, Any]]:
    """
    Filter a list of TMDB movies to the requested difficulty tier.
    Uses the pre-computed 'difficulty' field first; falls back to popularity percentile.
    """
    if not movies:
        return movies

    # Prefer pre-computed difficulty labels
    labelled = [m for m in movies if m.get("difficulty") == difficulty]
    if len(labelled) >= 15:
        return labelled

    # Fallback: split by popularity percentile
    if len(movies) < 30:
        return movies
    sorted_movies = sorted(movies, key=lambda m: float(m.get("popularity", 0)), reverse=True)
    total = len(sorted_movies)
    if difficulty == "easy":
        return sorted_movies[: max(20, total // 3)]
    if difficulty == "medium":
        start = total // 3
        end = (2 * total) // 3
        return sorted_movies[start:end]
    # hard
    return sorted_movies[(2 * total) // 3 :]


class TMDBClient:
    """Synchronous TMDB client using httpx."""

    def __init__(self, api_key: str, base_url: str = "https://api.themoviedb.org/3") -> None:
        self.api_key = api_key
        self.base_url = base_url
        self._client = httpx.Client(
            base_url=base_url,
            timeout=10.0,
            headers={"Accept": "application/json"},
        )

    def close(self) -> None:
        self._client.close()

    def _get(self, path: str, params: dict[str, Any] | None = None) -> dict[str, Any]:
        params = params or {}
        params["api_key"] = self.api_key
        resp = self._client.get(path, params=params)
        resp.raise_for_status()
        return resp.json()  # type: ignore[no-any-return]

    def fetch_movies_batch(
        self,
        languages: str = "hi|ta|te|ml",
        pages: int = 5,
        hindi_only: bool = False,
        sort_by: str = "popularity.desc",
        extra_params: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]:
        """
        Fetch `pages` pages of discover results for Indian movies.
        Returns a flat list of normalized movie dicts with difficulty labels.

        Pass `extra_params` to forward additional TMDB discover filters
        (e.g. year range, genre IDs) generated by the AI engine.
        """
        lang_filter = "hi" if hindi_only else languages
        all_movies: list[dict[str, Any]] = []
        seen_ids: set[str] = set()
        base_params: dict[str, Any] = {
            "with_original_language": lang_filter,
            "region": "IN",
            "sort_by": sort_by,
            "include_adult": "false",
            "vote_count.gte": "10",
        }
        if extra_params:
            base_params.update(extra_params)

        for page in range(1, pages + 1):
            try:
                data = self._get(
                    "/discover/movie",
                    params={**base_params, "page": page},
                )
                for raw in data.get("results", []):
                    movie_id = str(raw.get("id", ""))
                    if movie_id and movie_id not in seen_ids:
                        seen_ids.add(movie_id)
                        all_movies.append(_parse_movie(raw))
            except httpx.HTTPError as exc:
                logger.warning("TMDB page %d failed: %s", page, exc)
                break

        logger.info(
            "Fetched %d movies from TMDB (pages=%d, languages=%s)",
            len(all_movies),
            pages,
            lang_filter,
        )
        return all_movies

    def search_movie(self, title: str, year: int | None = None) -> dict[str, Any] | None:
        """
        Search TMDB for a movie by title (optional year). Returns normalized movie dict or None.
        Used only for AI-only mode (no TMDB batch available).
        """
        params: dict[str, Any] = {
            "query": title,
            "include_adult": "false",
        }
        if year is not None:
            params["year"] = year
        try:
            data = self._get("/search/movie", params=params)
            results = data.get("results", [])
            if not results:
                return None
            return _parse_movie(results[0])
        except Exception as exc:
            logger.debug("TMDB search failed for %r: %s", title, exc)
            return None
